version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - shopnet

  postgres-orders:
    image: postgres:15
    environment:
      POSTGRES_USER: orders
      POSTGRES_PASSWORD: orders
      POSTGRES_DB: orders_db
    ports:
      - "5433:5432"
    networks:
      - shopnet

  postgres-payments:
    image: postgres:15
    environment:
      POSTGRES_USER: payments
      POSTGRES_PASSWORD: payments
      POSTGRES_DB: payments_db
    ports:
      - "5434:5432"
    networks:
      - shopnet

  orders-service:
    build: ./orders-service
    depends_on:
      - rabbitmq
      - postgres-orders
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-orders:5432/orders_db
      SPRING_DATASOURCE_USERNAME: orders
      SPRING_DATASOURCE_PASSWORD: orders
      SPRING_RABBITMQ_HOST: rabbitmq
    ports:
      - "8081:8080"
    networks:
      - shopnet

  payments-service:
    build: ./payments-service
    depends_on:
      - rabbitmq
      - postgres-payments
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-payments:5432/payments_db
      SPRING_DATASOURCE_USERNAME: payments
      SPRING_DATASOURCE_PASSWORD: payments
      SPRING_RABBITMQ_HOST: rabbitmq
    ports:
      - "8082:8080"
    networks:
      - shopnet

  api-gateway:
    build: ./api-gateway
    depends_on:
      - orders-service
      - payments-service
    ports:
      - "8080:8080"
    networks:
      - shopnet

networks:
  shopnet:
    driver: bridge 