server:
  port: 8080
spring:
  application:
    name: orders-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/orders_db}
    username: ${SPRING_DATASOURCE_USERNAME:orders}
    password: ${SPRING_DATASOURCE_PASSWORD:orders}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  # rabbitmq:
  #   host: ${SPRING_RABBITMQ_HOST:localhost}
  #   port: 5672
  #   username: guest
  #   password: guest
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
logging:
  level:
    org.springframework: INFO 